[package]
name = "googly-blocks"
version = "0.1.91"
authors = ["LambdaXymox <lambda.xymox@gmail.com>"]
build = "build.rs"

[dependencies]
glfw = "0.36.0"
log = "0.4.8"
toml = "0.4.8"
bmfa = { git = "https://github.com/lambdaxymox/bmfa" }
file_logger = { git = "https://github.com/lambdaxymox/file-logger" }
lean_cgmath = { git = "https://github.com/lambdaxymox/lean-cgmath" }
mini_obj = { git = "https://github.com/lambdaxymox/mini-obj" }
teximage2d = { git = "https://github.com/lambdaxymox/teximage2d" }

[build-dependencies]
gl_generator = "0.14.0"

[profile.dev]
debug = true

[features]
build_for_install = []
