[package]
name = "googly-blocks"
version = "0.1.18"
authors = ["LambdaXymox <lambda.xymox@gmail.com>"]
build = "build.rs"

[dependencies]
glfw = "0.25.0"
log = "0.4.6"
stb_image = "0.2.2"
serde = "1.0.80"
serde_derive = "1.0.80"
toml = "0.4.8"
cgcamera = { git = "https://github.com/lambdaxymox/cgcamera" }
file_logger = { git = "https://github.com/lambdaxymox/file-logger" }
lean_cgmath = { git = "https://github.com/lambdaxymox/lean-cgmath" }
wavefront_obj = { git = "https://github.com/lambdaxymox/wavefront-obj" }

[build-dependencies]
gl_generator = "0.10.0"

[profile.dev]
debug = true

[features]
build_for_install = []
