[package]
name = "googly-blocks"
version = "0.1.37"
authors = ["LambdaXymox <lambda.xymox@gmail.com>"]
build = "build.rs"

[dependencies]
glfw = "0.32.0"
log = "0.4.6"
toml = "0.4.8"
bmfa = { git = "https://github.com/lambdaxymox/bmfa" }
cgcamera = { git = "https://github.com/lambdaxymox/cgcamera" }
file_logger = { git = "https://github.com/lambdaxymox/file-logger" }
lean_cgmath = { git = "https://github.com/lambdaxymox/lean-cgmath" }
mini_obj = { git = "https://github.com/lambdaxymox/mini-obj" }
teximage2d = { git = "https://github.com/lambdaxymox/teximage2d" }

[build-dependencies]
gl_generator = "0.13.1"

[profile.dev]
debug = true

[features]
build_for_install = []
